---
title: "How To Cite Our Work"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How To Cite Our Work}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

If you use this software in your research, please cite the references listed
below.

## The Sparse Marginal Epistasis Test (SME)


Stamp J, Smith Pattillo S, Weinreich D, Crawford L (2025). Sparse modeling of 
  interactions enables fast detection of genome-wide epistasis in biobank-scale 
  studies. biorxiv, <https://doi.org/10.1101/2025.01.11.632557>

Stamp J & Crawford L (2025). smer: Sparse Marginal Epistasis Test.
<https://github.com/lcrawlab/sme>, <https://lcrawlab.github.io/sme/>


## The multivariate Marginal Epistasis Test (mvMAPIT)

Stamp J, DenAdel A, Weinreich D, Crawford, L (2023). Leveraging the Genetic
Correlation between Traits Improves the Detection of Epistasis in Genome-wide
Association Studies. G3 Genes|Genomes|Genetics 13(8),
jkad118; doi: <https://doi.org/10.1093/g3journal/jkad118>

Stamp J, Crawford L (2022). mvMAPIT: Multivariate Genome Wide Marginal
Epistasis Test. <https://github.com/lcrawlab/mvMAPIT>,
<https://lcrawlab.github.io/mvMAPIT/>


## The Marginal Epistasis Test (MAPIT)

Crawford L, Zeng P, Mukherjee S, & Zhou X (2017). Detecting epistasis with the
marginal epistasis test in genetic mapping studies of quantitative traits.
PLoS genetics, 13(7), e1006869. <https://doi.org/10.1371/journal.pgen.1006869>
